### PR TITLE
Added index.html page

### PR DESCRIPTION
**Pull request by ManasSahni**

### CODE REVIEW

**Comment by hot9cups** [comment]
@ManasSahni I appreciate the participation, but the issue clearly says the PR has to be of a website that's functional, has all the required pages and is integrated. This is merely a home page, there's no provisions for forms, anchor tag links are empty and a lot of other requirements are missing. Please make the PR as per the specifications instead of half-cooked ones like these.

**Comment by ManasSahni** [comment]
But why have you marked it invalid atleast I had put some efforts.

**Comment by hot9cups** [comment]
If it isn't marked invalid, it counts towards Hacktoberfest. Low quality PRs that don't actually add any value to a project aren't worthy of being counted for hacktoberfest.

**Comment by ManasSahni** [comment]
Can I add a 6 page website that I created a month ago . You can use it as a
template.

**Comment by hot9cups** [comment]
If you can make the changes to it to suit my requirements go ahead. I will not be able to accept a mere template

**Pull request closed without merging**
